# Generated by Django 5.1 on 2024-10-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screwmycodein", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("youtube", "Youtube"),
                            ("soundcloud", "Soundcloud"),
                            ("bandcamp", "Bandcamp"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.TextField()),
                ("title", models.TextField()),
                ("image", models.TextField()),
                ("audio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screwmycodein.audio",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Bandcamp",
        ),
        migrations.DeleteModel(
            name="Soundcloud",
        ),
        migrations.DeleteModel(
            name="Youtube",
        ),
    ]
