# Generated by Django 5.1 on 2025-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screwmycodein', '0002_audio_hit_delete_bandcamp_delete_soundcloud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioV2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('image', models.TextField()),
                ('audio', models.TextField()),
            ],
        ),
    ]
