# Generated by Django 5.1 on 2025-07-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screwmycodein', '0003_audiov2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screwmycodein.audiov2')),
            ],
        ),
    ]
