# Generated by Django 5.1 on 2025-07-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screwmycodein', '0004_hitv2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hit',
        ),
    ]
