# Generated by Django 5.1 on 2025-07-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screwmycodein", "0005_delete_hit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Audio",
        ),
    ]
