# Generated by Django 5.1 on 2025-07-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screwmycodein", "0006_delete_audio"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AudioV2",
            new_name="MediaModel",
        ),
    ]
