# Generated by Django 5.1 on 2025-07-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screwmycodein", "0007_rename_audiov2_mediamodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hitv2",
            old_name="audio",
            new_name="media",
        ),
    ]
