django_secret: django_secret
webhook_secret: webhook_secret
jwt_secret: jwt_secret

venv_path: /path/to/venv/bin/activate
app_path: /path/to/django

allowed_hosts: []
allowed_origins: []

mysql:
  name: name
  user: root
  pass: root
  host: localhost
  port: 3306
