name: docker

on:
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup docker build
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          repository: ${{ github.repository }}/${{ env.IMAGE }}:latest
